dist: focal
language: node_js
node_js:
  - 18
install:
  - npm install -g codecov
before_script:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm run build
after_success:
  - npm run cover
  - codecov